apiVersion: v1
kind: Service
metadata:
  name: mediawiki
spec:
  selector:
    app: mediawiki
  ports:
    - protocol: TCP
      port: {{ .Values.mediawiki.port }}
      targetPort: {{ .Values.mediawiki.port }}