apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: {{ .Values.mediawiki.image }}
          ports:
            - containerPort: {{ .Values.mediawiki.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.mediawiki.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.mediawiki.port }}
            initialDelaySeconds: 20
            periodSeconds: 5